linters:
    NameFormat:
        convention: '[a-z]+(((__)|(--?))[a-z]+)*'
    SelectorFormat:
        convention: '[a-z]+(((__)|(--?))[a-z]+)*'
    Indentation:
        width: 2
    SingleLinePerProperty:
        enabled: true
        allow_single_line_rule_sets: false
    ImportantRule:
        enabled: false
    ColorVariable:
        enabled: true

