name: Sam Beckham
markdown: kramdown
permalink: /:categories/:title
exclude: ['config', 'README.md']
include: ['.htaccess']
permalink: wrote/:title.html

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: article

jekyll-crosspost_to_medium:
    enabled: true
    # cache: .jekyll-crosspost_to_medium
    status: draft
    # license: all-rights-reserved
    # backdate: true
