name: Sam Beckham
markdown: kramdown
permalink: /:categories/:title
exclude: ['config', 'README.md']
include: ['.htaccess']
permalink: wrote/:title.html

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: article